### ISSUE TITLE
make integration with travis-ci

### ISSUE THREAD

**Issue by darjeeling** [naver/hubblemon#4]
for contributing, you need to make integration with CI and run tests
in these days, most of open sources are using traivs-ci
please make integration.

**Comment by lynix94** [comment]
Thanks for notification. I'll integrate soon.

**Comment by lynix94** [comment]
integrate with travis-ci 
But now, It's restricted that using /proc/diskstats in travis vm which is used for collect_client.
(Should find other way later)
